###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    postgres:
        container_name: simpleapi-postgres
        restart: unless-stopped
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=simpleapi_user
            - POSTGRES_PASSWORD=simpleapi_pass
            - POSTGRES_DB=simpleapi_db
        ports:
            - '11004:5432'

    pgbouncer:
        container_name: simpleapi-db
        depends_on: 
            - postgres
        restart: unless-stopped
        image: edoburu/pgbouncer:latest
        extra_hosts:
            - 'giscloud.local:172.30.0.1'
        ports:
            - 5432:5432
        environment:
            DB_USER: simpleapi_user
            DB_PASSWORD: simpleapi_pass
            DB_NAME: simpleapi_db
            DB_HOST: simpleapi-postgres
            POOL_MODE: transaction
            MAX_CLIENT_CONN: 100
            DEFAULT_POOL_SIZE: 20


    webserver:
        container_name: simpleapi-webserver
        restart: unless-stopped
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './var/logs/nginx:/var/log/nginx'
        ports:
            - '11000:80'

    php-fpm:
        container_name: simpleapi-php-fpm
        restart: unless-stopped
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
            - './var/logs:/var/log'

volumes:
    pgdata:
