status:
    path: /status
    controller: App\Controller\StatusController::status
    method: GET
    description: Check if application is online
    request: null
    status_code: 200
    auth_required: false

test:
    path: /test/{parameter}/{parameter2}
    controller: App\Controller\TestController::test
    method: POST
    description: Test endpoint used for testing parameters and DTOs
    request: App\Dto\TestRequestDto
    status_code: 200
    auth_required: false

# Auth

auth_token:
    path: /auth/token
    controller: App\Controller\AuthController::issueToken
    method: POST
    description: Get an API access token
    request: App\Dto\Auth\TokenIssueRequest
    status_code: 201
    auth_required: false

auth_list:
    path: /auth/token
    controller: App\Controller\AuthController::listTokens
    method: GET
    description: List hashes of active API access tokens
    request: null
    status_code: 200
    auth_required: true

auth_revoke:
    path: /auth/token/{token_id}
    controller: App\Controller\AuthController::revokeToken
    method: DELETE
    description: Revoke an API access token
    request: null
    status_code: 204
    auth_required: true

auth_validate:
    path: /auth/validate
    controller: App\Controller\AuthController::validateToken
    method: GET
    description: Check if sent API access token is valid
    request: null
    status_code: 200
    auth_required: true
