status:
    path: /status
    controller: App\Controller\StatusController::status
    method: GET
    description: Check if application is online

test:
    path: /test/{parameter}/{parameter2}
    controller: App\Controller\TestController::test
    method: POST
    description: Test endpoint used for testing parameters and DTOs
